### ISSUE TITLE
AAPT2 is changing resources IDs

### ISSUE THREAD

**Issue by barreeeiroo** [barreeeiroo/appinventor-sources#6]
I solved the previous issue and even signed the AAB (to be suitable for Play Store). Currently, it can totally build the AAB and make it for production.
The only issue is the `abc_vector_test` one that I commented in the meeting.

So, after extracting the resources IDs from both AAB and normal APK, I found out that the IDs don't match. I've attached here the generates one from AAPT and AAPT2.

> ✅ abc_vector_test = 0x7f020053
> [aapt.txt](https://github.com/barreeeiroo/appinventor-sources/files/4821102/aapt.txt)
> :x: abc_vector_test = 0x7f060053
> [aapt2.txt](https://github.com/barreeeiroo/appinventor-sources/files/4821103/aapt2.txt)

All resources have different IDs, so I don't really know what's going on.

**Comment by barreeeiroo** [comment]
BTW, forgot to mention that now the AAB contains the correct XML file, not like in the meeting which removed data from <path>.

**Comment by ewpatton** [comment]
Does the app work? If it works, I think it's probably fine. My guess is that by processing the items in a different order aapt2 ends up assigning different IDs than aapt, which processes them in bulk.

**Comment by barreeeiroo** [comment]
Nope, it does not. I get the same "resources not found" error, and I suspect it's due to IDs.

**Comment by barreeeiroo** [comment]
I'm posting here the logcat info. I was not able to resolve it yet:

```
06-25 16:25:28.913  1893  2026 I ActivityManager: Start proc 23721:edu.mit.appinventor.aicompanion3/u0a1349 for activity edu.mit.appinventor.aicompanion3/.Screen1 caller=com.miui.home
06-25 16:25:28.917 23721 23721 E or.aicompanion: Not starting debugger since process cannot load the jdwp agent.
06-25 16:25:28.917 21766 21766 D Launcher_WallpaperUtils: changeStatusBarMode:false
06-25 16:25:28.922 21766 21766 D Launcher.Lifecycle: onWindowFocusChanged:false,UserHandle{0},7c06d9e,true
06-25 16:25:28.927  1893  3804 D CompatibilityInfo: mCompatibilityFlags - 0
06-25 16:25:28.927  1893  3804 D CompatibilityInfo: applicationDensity - 480
06-25 16:25:28.927  1893  3804 D CompatibilityInfo: applicationScale - 1.0
06-25 16:25:28.932  1893  3804 I set_top_app: success /proc/23721/task/23721/top_app:1
06-25 16:25:28.933  1893  3804 D CompatibilityInfo: mCompatibilityFlags - 0
06-25 16:25:28.933  1893  3804 D CompatibilityInfo: applicationDensity - 480
06-25 16:25:28.933  1893  3804 D CompatibilityInfo: applicationScale - 1.0
06-25 16:25:28.933  4727  4738 I ProcessMonitor: onForegroundInfoChanged: ForegroundInfo{mForegroundPackageName='edu.mit.appinventor.aicompanion3', mForegroundUid=11349, mForegroundPid=23721, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10028, mLastForegroundPid=21766, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=1}
06-25 16:25:28.935  5942  6012 D PowerKeeper.AppBgIdle: setUidState, uid = 11349 allow = false
06-25 16:25:28.935  1893  3804 W ActivityManager: Request to remove task ignored for non-existent task 8229
06-25 16:25:28.935  1893  3827 V LocationPolicy: writePolicyLocked()
06-25 16:25:28.953 10289 12764 I CloudSettingsProvider: uriMatch : 2
06-25 16:25:28.956  1893  2151 I Timeline: Timeline: App_transition_ready time:1019978933
06-25 16:25:28.964 10289 12764 I CloudSettingsProvider: uriMatch : 2
06-25 16:25:28.975 23721 23721 I or.aicompanion: The ClassLoaderContext is a special shared library.
06-25 16:25:29.005   913  1227 I ThermalEngine: handle_thresh_sig: SS Id SS-CLUSTER1-SP0, Read xo_therm 39000mC
06-25 16:25:29.016 23721 23721 I Perf    : Connecting to perf service.
06-25 16:25:29.038 23721 23721 I MultiDex: VM with version 2.1.0 has multidex support
06-25 16:25:29.038 23721 23721 I MultiDex: install: doIt = false
06-25 16:25:29.038 23721 23721 I MultiDex: VM has multidex support, MultiDex support library is disabled.
06-25 16:25:29.048 23721 23721 I ReplApplication: ACRA Not Active
06-25 16:25:29.110 23721 23721 D AppInventorCompatActivity: Setting classic mode from YAIL: false
06-25 16:25:29.120 23721 23721 E or.aicompanion: Resource 7f020053 is a complex map type.
06-25 16:25:29.120 23721 23721 D AndroidRuntime: Shutting down VM
--------- beginning of crash
06-25 16:25:29.121 23721 23721 E AndroidRuntime: FATAL EXCEPTION: main
06-25 16:25:29.121 23721 23721 E AndroidRuntime: Process: edu.mit.appinventor.aicompanion3, PID: 23721
06-25 16:25:29.121 23721 23721 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{edu.mit.appinventor.aicompanion3/edu.mit.appinventor.aicompanion3.Screen1}: android.content.res.Resources$NotFoundException: Resource ID #0x7f020053
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2985)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6878)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
06-25 16:25:29.121 23721 23721 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f020053
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.content.res.Resources.getValue(Resources.java:1345)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded(AppCompatDrawableManager.java:235)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImpl.<init>(AppCompatDelegateImpl.java:260)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:182)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at com.google.appinventor.components.runtime.AppInventorCompatActivity.onCreate(AppInventorCompatActivity.java:81)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at com.google.appinventor.components.runtime.Form.onCreate(Form.java:296)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at com.google.appinventor.components.runtime.ReplForm.onCreate(ReplForm.java:123)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at edu.mit.appinventor.aicompanion3.Screen1.onCreate(Screen1.yail:10003)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7232)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7221)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965)
06-25 16:25:29.121 23721 23721 E AndroidRuntime:        ... 11 more
06-25 16:25:29.127  3115  3152 I octvm_klo: klo lock
06-25 16:25:29.128  1893  3804 W ActivityManager:   Force finishing activity edu.mit.appinventor.aicompanion3/.Screen1
```

**Comment by barreeeiroo** [comment]
It's working! :tada:💪

After trying lots and lots of solutions, I realized that maybe AAPT was not needed, and I was using the R.txt file generated from AAPT rather than from AAPT2. And after looking documentation, I was not able to find the `--output-text-symbols` flag (but it seems I did not search properly because it was there...). With that, I can just generate the R.txt file, pass it to Dx and build the app.
I'll commit the working procedure, but I'll clean it up before proceeding with Compiler refactor.

Cross-linking here the issue that helped solving it (yeah, from Chromium project :joy:):
https://bugs.chromium.org/p/chromium/issues/detail?id=820460

---

MIT App Inventor Companion as an Android App Bundle: https://drive.google.com/file/d/1N22RMQwObp_gZByyfSSaguocG4kGFyDa/view?usp=sharing

|*Considering APK from AAB with platform-specific version*|APK|AAB|
|----------------------|--------------|-------------|
|Packed|~15MB|~9MB|
|Unpacked|~38MB|~28MB|
